### ISSUE TITLE
Is there a reason I can play animations only one time on mobile?

### ISSUE THREAD

**Issue by Squ34k3rZ** [daniel-lundin/snabbt.js#1]
When I view the docs website on my phone, the animations are awesome! Good job!

I'm wondering if there's a reason I can hit the attention animation button many times on desktop but it'll only play one time on my iphone. Thanks!

Would consider using this for the forms on my mobile site.

**Comment by daniel-lundin** [comment]
Thanks!

Hmm, no it's must be a bug.
Thanks for reporting, I will investigate.

**Comment by daniel-lundin** [comment]
I can not reproduce this with my iPhone 5s(iOS 8) on either Chrome or Safari.
What version are you running ?

**Comment by Squ34k3rZ** [comment]
I think it's the one before iOS 8 ;)

I'll try to remember to check back later. My iphone is a 4S if that helps.

**Comment by bon22801** [comment]
It also happens to my iphone4 (iOS7.1.2). All the examples can only be clicked once and the easing examples don't work.

**Comment by daniel-lundin** [comment]
I was able to reproduce it on my iPad2 with iOS 7. There was a perspective bug in the documentation(not in snabbt.js). It should work now.
