### ISSUE TITLE
Can you add support for SVG elements?

### ISSUE THREAD

**Issue by Emasoft** [daniel-lundin/snabbt.js#10]
Can you add support and examples for SVG elements? I make most of my UI elements in SVG with Inkscape and I'd love to use snabbt to animate them. Thank you!

**Comment by daniel-lundin** [comment]
I'm not SVG expert, but it seems that it's already working:
```
<!DOCTYPE html>
<html>
<body>

<svg height="500" width="500">
  <ellipse id="e1" cx="50" cy="50" rx="50" ry="50" style="fill:red" />
</svg>

<script src="snabbt.min.js"></script>
<script>
snabbt(document.getElementById('e1'), {
  position: [300, 0, 0],
  easing: 'ease',
  loop: Infinity
});
</script>
</body>
</html>
```

So please try it out, and let me know if you run into any problems..

**Comment by daniel-lundin** [comment]
I'll close this until any actual bug is reported.
