### ISSUE TITLE
Browser Support List

### ISSUE THREAD

**Issue by infinitation** [daniel-lundin/snabbt.js#18]
I didn't see a supported browser list other than modern browsers. Can you be more specific such as IE9+ FF32+, etc...  would love to save some time in testing if you already have the data.

**Comment by daniel-lundin** [comment]
Unfortunately not. The things the library uses that could be a problem for older browsers are CSS3 transforms and requestAnimationFrame. According to caniuse.com this makes it:
IE10+
FF33+
Chrome31+
Safari 7.1+
Opera 26+
iOS Safari 7.1
Android Browser 4.4+
Chrome for Android 39+

But this is just theoretical.
I will download some old browsers to see if I can get some more reliable data.

**Comment by sahat** [comment]
Would recommend adding something like https://github.com/sahat/satellizer#browser-support in the README for better illustration.

**Comment by daniel-lundin** [comment]
Updated readme with browser support.
Resorting to fallbacks for 3d transforms and requestAnimationFrame will not give smooth animations. So I rather just support the browsers that have these features than support older versions while giving a sub-optimal experience.
Sorry :(

**Comment by chchrist** [comment]
How about webview support on android and ipad?
