### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by gurre** [daniel-lundin/snabbt.js#2]
Awesome code! But what version is this? Still beta?

**Comment by codef0rmer** [comment]
I think, yes, [The site](http://daniel-lundin.github.io/snabbt.js/) shows this message "Warning: snabbt.js is under development, breaking changes could occur. This document should be seen as a draft."

**Comment by daniel-lundin** [comment]
It hasn't been heavily tested so I wanted to see if any issues are reported first.
The API will probably not change much at all.

Planning for a first release this weekend. Thanks for your patience.

**Comment by daniel-lundin** [comment]
The initial (beta) release is out: https://github.com/daniel-lundin/snabbt.js/releases/tag/v0.1.0
Give it a spin!
