### ISSUE TITLE
Using CJS/AMD/ES6 modules instead of just concatenation

### ISSUE THREAD

**Issue by chicoxyzzy** [daniel-lundin/snabbt.js#22]
I think snabbt.js should use CJS/AMD/ES6 modules instead of just concatenation on build step. For now we have multiple `var snabbtjs = snabbtjs || {};` in various places of snabbt.js file. This is kinda ugly and not jsHint/jsLint valid. Instead we can import modules and extend `snabbt.prototype`.

**Comment by daniel-lundin** [comment]
Yes, it' not very pretty. But I would like to support both CommonJS and AMD loaders so I need to figure out how to do this. Right now the same file can used with for RequireJS, browserify and as a global module, which is quite nice.

If I use the CommonJS-module system for example, I would need to transform it into AMD for RequireJS to work right?

I will have to investigate..

**Comment by chicoxyzzy** [comment]
No, I mean using modules **inside** snabbt.js project not wrapper for builded version of snabbt.js. After building snabbt with (for example) Browserify or WebPack we'll just have concatenated file but without multiple `var snabbtjs = snabbtjs || {};` lines

**Comment by chicoxyzzy** [comment]
Also this should make snabbt more tests-friendly (but needs some refactoring as well). I already have my own local branch using Browserify for building snabbt. I think I can represent it soon (lacking free time for now)

**Comment by daniel-lundin** [comment]
Cool, it would be very much welcome. I'm looking forward to it.

**Comment by chicoxyzzy** [comment]
Wrapping files in modules greatly increases library size so I think it's not worth it
