### ISSUE TITLE
Add cdn info

### ISSUE THREAD

**Issue by PeterDaveHello** [daniel-lundin/snabbt.js#28]
Hi @daniel-lundin,

I'm Peter from cdnjs.com,

I wonder if you would like to add cdn info in the readme or the website?

This is the page we provide cdn for snabbt.js - https://cdnjs.com/libraries/snabbt.js

Thanks!

**Comment by daniel-lundin** [comment]
Added to readme!

**Comment by PeterDaveHello** [comment]
Thanks.
