### ISSUE TITLE
Provides tern plugin for snabbt.js

### ISSUE THREAD

**Issue by angelozerr** [daniel-lundin/snabbt.js#3]
Hi @daniel-lundin,

I think it should be cool if you could provide a tern plugin for snabbt.js to have completion, navigation, hover, etc inside a JS Editor (Web Browser, Sublime Text, Vim, Emacs, Eclipse, etc).

If you don't know ternjs, see demo at http://ternjs.net/doc/demo.html

Writing a tern plugin is very easy. See https://github.com/marijnh/tern/blob/master/defs/ and https://github.com/marijnh/tern/blob/master/plugin

With tern you could manage those cases inside JS editor : 

```javascript
s // Ctrl+Space shows snabbt
```

```javascript
snabbt(element, { 
// Ctrl+Space shows position, rotation, duration, etc
```

If you are interested with this tern plugin, I could help you to write it. Tell me.

**Comment by daniel-lundin** [comment]
Hi,

It would be very cool indeed.
I'm guessing it wouldn't be too much work since the set of operations is quite limited in snabbt.js.

Let me know if I can be of assistance.

**Comment by angelozerr** [comment]
> I'm guessing it wouldn't be too much work since the set of operations is quite limited in snabbt.js.

No I think it's easy to do. If you create in your github a project called tern-snabbt, I could write it and create a PR.

**Comment by daniel-lundin** [comment]
Ok, cool. https://github.com/daniel-lundin/tern-snabbt

**Comment by angelozerr** [comment]
Thanks @daniel-lundin 

If I write a simple tern plugin for snabbt, are you OK to continue it and mantain it? If you need assistance to improve it or if you find bugs/limitations I'm OK to help you.

Are you OK with that?

**Comment by daniel-lundin** [comment]
Yes, of course!

Thanks a ton!

**Comment by angelozerr** [comment]
> Yes, of course!

Cool!

Please add a file to your github, I cannot fork it otherwise. Thanks

**Comment by daniel-lundin** [comment]
Ah, sorry. Added a readme file. Should be forkable now

**Comment by angelozerr** [comment]
@daniel-lundin see my PR at https://github.com/daniel-lundin/tern-snabbt/pull/1

It should be cool if you can add this screenshot : 

![ternsnabbtswithcodemirror](https://cloud.githubusercontent.com/assets/1932211/5596672/5f6ac4e6-9294-11e4-9b28-3d134c17fd42.png)

in yhe tern-snabbt wiki project (in images folder) in order image https://github.com/daniel-lundin/tern-snabbt/wiki/images/TernSnabbtsWithCodeMirror.png used in the README display the screenshot. Thanks

**Comment by daniel-lundin** [comment]
Awesome work, thanks!

Will add the image.

**Comment by angelozerr** [comment]
> Awesome work, thanks!

ternjs is awesome :)

I will integrate this tern plugin inside Eclipse with tern.java https://github.com/angelozerr/tern.java

Don't hesitate to create issues to improve the tern plugin if you need help.

**Comment by daniel-lundin** [comment]
Will try it out in vim to see if it can be improved.

Big thanks again! 👍

**Comment by angelozerr** [comment]
> Will try it out in vim to see if it can be improved.

Never used Vim.

Could you please update the screenshot with this image please (just remove tabs bar of webbrowser) : 
![ternsnabbtswithcodemirror](https://cloud.githubusercontent.com/assets/1932211/5596933/d8009a0c-9299-11e4-941e-e751dae8b1c9.png)

Thanks.

 * I think it misses some function (just used your doc in your website). 
 * I have not managed $element with jQuery, 
 * I have not managed from_* properties
 * we could manage completion for easing value : 'spring', etc
 * Attention animations will causes problems for completion for object configurable because there is 3 parameters, etc

Create an issue per problem if you cannot do it, and I will try to help you.

**Comment by daniel-lundin** [comment]
I updated the screenshot.

I'll try to fix the issues and will let you know if I run in to problems.
But focus now is to get out a proper release.
Will hopefully have time this weekend.
Cheers!

**Comment by angelozerr** [comment]
> Will try it out in vim to see if it can be improved.

Just for your information, you must use tern from github since tern is not released for object literal features.
