### ISSUE TITLE
Cannot set property 'webkitTransform' of undefined

### ISSUE THREAD

**Issue by ivkean** [daniel-lundin/snabbt.js#32]
I include file js in <head>, then i call something like:
snabbt('#btnPostComment', 'attention', {
                  position: [50, 0, 0],
                  springConstant: 2.4,
                  springDeacceleration: 0.9,
                });
and console error is:
Uncaught TypeError: Cannot set property 'webkitTransform' of undefined
Can you fix it ?
Thank you

**Comment by daniel-lundin** [comment]
The first parameter should be a reference to DOM-element, not a CSS-selector. 

Try document.getElementById('btnPostComment') as first parameter.
