### ISSUE TITLE
options.callback not invoked for attention style animations

### ISSUE THREAD

**Issue by mordendk** [daniel-lundin/snabbt.js#35]
I can see how this can be hard to determine, but looks like you're already handling some equilibriumReached or equilibriumPosition stuff.

ie.this works:

```javascript
snabbt(element, {
  position: [50, 0, 0],
  springConstant: 2.4,
  springDeacceleration: 0.9,
  callback: callback
});
```

these do not:

```javascript
snabbt(element, 'attention', {
  position: [50, 0, 0],
  springConstant: 2.4,
  springDeacceleration: 0.9,
  callback: callback
});

// or

snabbt(element, 'attention', {
  position: [50, 0, 0],
  springConstant: 2.4,
  springDeacceleration: 0.9
})
.then({
  callback: callback
});
```

**Comment by latima** [comment]
Why ?? Tell me

**Comment by daniel-lundin** [comment]
It's doable to get the callback working. Looking at the code I see that loop is not working either. I will add that as well. Hopefully later today.

I'm not sure if chaining with then()-calls makes any sense for attention animations. I don't think it's self-evident what a then-call should do.

**Comment by mordendk** [comment]
Thanks for a quick reply Daniel - don't hurry on my account :)

I see your point about then()-calls, but I still think it makes sense. I get the notion of a promise resolving, an intuitive way of working with async stuff - like animations. So if the config object takes a callback, a then()-call (promise) should always resolve as well - at least for consistency. Just my 2 cents.

The reason I have focus on the callbacks, is that it will extend the compatibility of snabbt.js with other big player frameworks. Right now I'm bridging it with AngularJS' animation framework and it works absolutely great. But it is crucial  that the framework knows when the animation is done and it's safe to go on updating it's view. Otherwise the 2-way binding might remove elements from the dom before they're done animating. Right now this is not possible with attention animations.

Lastly I just wanna say that I greatly appreciate the effort you have put in to this so far. It's a great experience writing complex animations, at least compared to doing it in CSS. Also I'm able to pair element properties with physics settings, like adjusting springMass based on the size of the dom element being animated. This opens up for new ways of reusing and thinking about animations, and is something I wouldn't  be able to do in CSS.

So good job Daniel, thank you :)

**Comment by daniel-lundin** [comment]
Thank you! Always fun to hear about how people are using the library.

I kind of regret using the word 'then' since a lot of people associate it with a promise, which it really isn't in this case. I think a lot of people would expect `then()` to take a function that would be called when the animation is completed. Something like 'queue' or 'chain' would probably be more appropriate.

That being said, the latest from master now has callbacks on attentions animations.

It will be out in the next release.
