### ISSUE TITLE
How to achieve transform-origin in snabbt

### ISSUE THREAD

**Issue by zhangmeng712** [daniel-lundin/snabbt.js#39]
I'm using the snabbt.js to do the animation, I want to rotate a div from specific origin,
like in css  { transform: rotateX(30deg);transform-origin: 0px 180px;} How can I achieve this by using 
snabbt?

**Comment by daniel-lundin** [comment]
There are three ways I can think of:

1. Set the transform-origin with css.
2. Use a combination of position and offset

```
snabbt(element, {
  fromPosition: [0, 90, 0],
  position: [0, 90, 0],
  offset: [0, -90, 0],
  rotation: [Math.PI/6, 0, 0]
});
```

3. Use the valueFeeder function and perform translationY(-90px) rotateX(30deg) followed by translationY(90px):
```
snabbt(element, {
  valueFeeder: function(i, matrix) {
    return matrix.translate(0, -90, 0).rotateX(i*(Math.PI/6)).translate(0, 90, 0);
  }
});
```

None of these are straight-forward so I'm thinking of adding a transformOrigin option to the animation configuration.
