### ISSUE TITLE
Chaining broken: previous states are not set to 'from' when changing 'position' and 'scale'

### ISSUE THREAD

**Issue by bravedick** [daniel-lundin/snabbt.js#42]
snabbt(_this.cursor, {
                fromPosition: [210, 555, 0],
                position: [150, 190, 0],
                duration: 1000,
                easing: 'ease'
            }).then({
                position: [150, 190, 0],
                scale: CURSOR.pressedScale,
                duration: CURSOR.pressedDuration,
                callback: function() {
                    _this.drag.style.visibility = 'visible';
                    snabbt(_this.drag, {
                        position: [-100, -30, 0],
                        duration: 800,
                        easing: 'ease'
                    });
                    snabbt(_this.cursor, {
                        position: [50, 160, 0],
                        scale: CURSOR.pressedScale, // here
                        duration: 800,
                        easing: 'ease',
                        callback: function() {
                        }
                    });
                }
            });

we need to duplicate `scale: CURSOR.pressedScale`, cause it will be set to [1, 1] when `position: [50, 160, 0],` is set.

**Comment by daniel-lundin** [comment]
Thanks for the report, I will look into it. Might be that the callback is executed before the saved state is stored..

Just had my first baby, that's the reason for the slow responses.. :)

**Comment by bravedick** [comment]
Congrats! :)

Clean up version here: http://jsfiddle.net/s81ptssk/ Circle scaled back to [1, 1].

**Comment by daniel-lundin** [comment]
Ah, now I see, great example.
Actually the fromScale is set to [5, 5] (it starts from scale [5,5] in the second part of the animation) but the end scale defaults to [1, 1] which is why it shrinks back again.
Maybe I should change it so that it keeps the scale(and other properties) the same if you don't explicitly set it to something else. I guess that's more convienient.
I will give it some thought!

**Comment by daniel-lundin** [comment]
This is fixed in master, will be out in the next release. (In a few days)

**Comment by bravedick** [comment]
Thanks!
