### ISSUE TITLE
Half pixels, blur text

### ISSUE THREAD

**Issue by vennamo** [daniel-lundin/snabbt.js#43]
The translate3d matrix has half-pixel values...that causes text blurriness on chrome. Not sure if this is really an issue. But in my case I rounded the values in matrixToCSS function to nearest integer to solve the problem. Im not sure either why sbabbt makes full integer values to such a long floats.
Example position: [0, 374, 0]  is 374.2063598633 in the matrix.

**Comment by daniel-lundin** [comment]
During an animation sub-pixel values are ok(even preferable, it often looks smoother), but when the animation is finished the position should be very close to 374 in your case. So something is not working correctly there right now. I will have a look into it.
Thanks!

**Comment by vennamo** [comment]
Ok. Let's see if you find something.

**Comment by daniel-lundin** [comment]
Btw, are you using spring easings? I see that it might be an issue there with the end state.

**Comment by vennamo** [comment]
Yes I am.

**Comment by daniel-lundin** [comment]
I found the bug, it's fixed in master now. A new release is coming in the next few days as well.

**Comment by vennamo** [comment]
Much better know. Thanks. 
A little mismatch in the options name and the actual option in the code:
In document page: springDeaccelaration
In the code: springDeceleration

**Comment by daniel-lundin** [comment]
Great!
And good catch, will update the documentation.
