### ISSUE TITLE
How to set initial positions for elements

### ISSUE THREAD

**Issue by kimmobrunfeldt** [daniel-lundin/snabbt.js#45]
I would like to have element initially out of the viewport before animating it inside the view with snabbt. In jQuery, I would do that by setting `top: -200px;` rule initially for the element, and animating top to 0. 

Since snabbt uses transforms, what would be the correct way to set the initial positions?

**Comment by daniel-lundin** [comment]
You could set `transform: translateY(-200px);` on the element initially. That transform will be overwritten as soon as the snabbt-animation starts. Then use fromPosition to make sure it starts from the same position.
```
snabbt(element, {
  fromPosition: [0, -200, 0]
});
```

**Comment by kimmobrunfeldt** [comment]
Thank you!
