### ISSUE TITLE
Is is possible add a method to remove all styles created by snabbt?

### ISSUE THREAD

**Issue by oak-tree** [daniel-lundin/snabbt.js#46]
Hey there! **Great work!!**

We are using snabbt in one of our project and so far so good. one small thing. sometimes when doing `translation effect` on element  and reset their position by taking them to 0,0,0. it changes the behavior of elements. like z-index and etc.. so after the `reseting transform` has been done we remove all `inline styles` from the elements. 

The question

Is it possible to have some `snabbt` method to clean `styles` that came from `snabbt`

Best,

Oak

**Comment by oak-tree** [comment]
What do you think on something like ?

## Option1
     snbbat(elements,{
                position : [ -(this.$el.width() + INT_GAP), 0, 0 ],
                easing : 'easeIn,
                duration : 450,
                }).({clearStyles:true})

## Options2
     snabbt(elements,{
                position : [ -(this.$el.width() + INT_GAP), 0, 0 ],
                easing : 'easeIn,
                duration : 450,
                callback: function(){snabbt(elements,{clearStyles:true}))
                })

**Comment by tommiehansen** [comment]
@oak-tree What's wrong with element.removeAttribute('style')?

Create a shorthand or something:

    // remove from single selector
    function clearStyle(e){
        e.removeAttribute('style');
    }

    // remove from multiple selectors
    function multiClearStyles(e){
        var i = 0, len = e.length;
        for(i;i<len;i++){ e.removeAttribute('style'); }
    }

...and just call clearStyle(element) on complete.

Would need a fix for jQuery like e[0] etc to get the raw element if using jQ.

**Comment by oak-tree** [comment]
well. because some elements can have some `presnabbit` styles. so maybe one wants to `reset` only `snabbt` styles

**Comment by tommiehansen** [comment]
@oak-tree As i said one could write a more complex func and add stuff like: `elem.style.removeProperty('some-style-property');`.

You shouldn't have inline styles on your elements to begin with though so you should just remove the style all together.

**Comment by daniel-lundin** [comment]
Since removing the styles is just a one-liner I don't see the need to wrap it within snabbt.

**Comment by oak-tree** [comment]
just think on the case where other plugins add some property to the element. one may want to cancel only `snabbt`  properties.
