### ISSUE TITLE
Percentage values

### ISSUE THREAD

**Issue by tommiehansen** [daniel-lundin/snabbt.js#47]
Position doesn't support percentage values. This is a problem for when one want to move something out of view and when at the same time the object that one is moving is of variable witdth, height etc (think responsive design and boxes that alter their widths depending on available screen width).

One could hack around this but it would be less performant and isn't an ideal solution.

**Comment by timuric** [comment]
Same issue here, it is pretty common to use % for animations, specially when building something responsive

**Comment by daniel-lundin** [comment]
Snabbt uses matrix3d under the hood(for performance reasons), that's why only pixel value and radians are supported. To allow percentage values I would need to include unit conversions and that's out of scope for snabbt.
