### ISSUE TITLE
Trigger callback once per collection

### ISSUE THREAD

**Issue by tommiehansen** [daniel-lundin/snabbt.js#48]
The callback function always triggers once per element in a collection, see example:
http://jsfiddle.net/tommiehansen/b01achLn/8/embedded/result/

It is desired that it only triggers once per animation no matter how many elements that is being animated.

**Comment by daniel-lundin** [comment]
Thanks for the feedback!

I decided to use the function initializers(introduced in 0.4.0) to solve this instead.
If a collection is animated, the callback-parameter is always called with two parameters, the current index of the element in the collection and to total number of elements in the collection.

This allows for triggering something in the callback only one time or one time for each completed element.

Example for triggering only for the first element:

```
$(".some-class").snabbt({
   position: [100, 0, 0],
   callback: function(i, total) {
    if(i === 0)
      doSomething();
   }
}); 
```

**Comment by tommiehansen** [comment]
Thanks for the response Daniel but i really don't think that solution is in the realms of something that one would expect (which will make the lib harder to understand). I also fail to understand why the default should be something unexpected; how often do one really want to fire 1x callback per collection of elements?

jQ animate, velocity.js, transit.js all fire 1x callback per animation rather than per collection of elements so below would easily work:

    var thing = $('.thing'),
          stuff = $('.stuff'),
          all = thing.add(stuff);

    all.animate('top','10px', function(){ doStuff(); }) // jquery
    all.velocity({ top: 10 }, { complete: function(){ doStuff(); } } // velocity.js
    all.transition({ y: 10 }, 0, function(){ doStuff(); }) // transit.js

I get that you might have a different philosophy behind snabbt.js but the sort of global callback is so oftently used so that littering if(x === y) would quickly bloat any code that one would use snabbt.js for.

**Comment by daniel-lundin** [comment]
Thanks for the elaborate answer, you make a good point. I don't want to remove the possibility to trigger a callback for each element though since I've found is useful myself on several occasions.
But as you say, "one callback for the whole collections" is probably what you would except most of the time.
So `callback` should probably work as you describe, and then create an an extra property for `perElementCallback` or something similar.
I'll give it some thought!

**Comment by tommiehansen** [comment]
@daniel-lundin Sounds great and i understand that there's a reason that it's constructed the way. Looking forward to reconstruct som codePen demos with snabbt.js soon. :)

**Comment by daniel-lundin** [comment]
Now I've finally found the time to look at this.
I've added a separate option `allDone` that will be triggered only once per collection.
The old complete is still there and works as it did before.

I will update the docs as well.
