### ISSUE TITLE
iOS 5 not working

### ISSUE THREAD

**Issue by Webysther** [daniel-lundin/snabbt.js#50]
Not work in Ipad 1

Mozilla/5.0 (iPad; CPU OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B206 Safari/7534.48.3

**Comment by Webysther** [comment]
Add the gist requestAnimationFrame polyfill fix this.

https://gist.github.com/paulirish/1579671

**Comment by daniel-lundin** [comment]
I've added a polyfill which should fix this.
Let me know if there still is problems (don't have a iOS 5 device to test with)
