### ISSUE TITLE
snabbt dont't work on andriod

### ISSUE THREAD

**Issue by mask2012** [daniel-lundin/snabbt.js#51]
in my test snabbt do not work on my andriod phones samsung s3, even simple width animation

**Comment by daniel-lundin** [comment]
What version of snabbt are you using?
Do you have an example of code that is not working?

Thanks.

**Comment by daniel-lundin** [comment]
I added a polyfill for requestAnimationFrame in 0.5.2.
It should fix the issue.
Please reopen if it doesn't solve the problem
