### ISSUE TITLE
Poor performance in Firefox for Android

### ISSUE THREAD

**Issue by simevidas** [daniel-lundin/snabbt.js#52]
I’m not sure if there’s anything you could do about this, but just letting you know that when running the Sticks demo in Firefox on a Nexus 7 2013 device, I get only around 2 FPS. For comparison, Chrome is within 12 and 47 FPS and the animation is visually acceptable.

Maybe we could file a bug at bugzilla.mozilla.org?

**Comment by daniel-lundin** [comment]
A lot has happened since this one so I'm not sure it's relevant.
Please reopen if you still experience problems..

**Comment by simevidas** [comment]
@daniel-lundin I’m sorry to have to inform you that the issue is still prevent. What FPS number do you get in Firefox on Android?
