### ISSUE TITLE
Cannot work on some android devices?

### ISSUE THREAD

**Issue by Voyga** [daniel-lundin/snabbt.js#53]
This is a great library, and this works well on my android device and ios device, but it is not working on some of my friends android devices (the whole program died when meet the function snabbt). Can this be fixed? Thank you.

**Comment by daniel-lundin** [comment]
Hi,

Do you have any device-info? What versions of android and what brand?

**Comment by Voyga** [comment]
I've tested 3 devices. My htc e8 (4.4.2) works well, Samsung S4 (4.3) and Samsung Note 2 (4.1) doesn't work.

**Comment by daniel-lundin** [comment]
Oh, that's not good.
What version of snabbt are you using?

**Comment by Voyga** [comment]
It should be the latest version.. I started using snabbt last week. Do you have an idea what cause this problem?

**Comment by daniel-lundin** [comment]
I haven't seen this issues before so there might be something in the later releases. Do you think you could try with a previous release? 0.4.0 perhaps?
I'm pretty swamped at the moment so I won't have time to look at it until after the weekend.

**Comment by Voyga** [comment]
@daniel-lundin I tried 0.4.0 and there's another problem. 

```javascript
snabbt(elem, {
    fromScale: [0.8, 0.8],
    scale: [1, 1],
    easing: "spring"
});
```

"fromScale" worked, but the animation didn't run.

**Comment by lovenick** [comment]
Ran into the same issue in the stock Android browser running on Samsung S3 w/ 4.4.2 and HTC One X+ w/ 4.1.1. Didn't do much investigation, but using a polyfill for requestAnimationFrame corrected the issue.  The performance of the animations took a big hit with this method.

**Comment by Voyga** [comment]
@lovenick Can you please show me how? I'm new to javascript... Thanks a lot.

**Comment by lovenick** [comment]
Place the gist below in your JS before any call to Snabbt.

https://gist.github.com/paulirish/1579671

The code will shim the window.requestAnimationFrame method if not available natively.

**Comment by Voyga** [comment]
@lovenick  It works, thank you.

**Comment by daniel-lundin** [comment]
I added a polyfill for requestAnimationFrame in 0.5.2
Please reopen if it doesn't solve the problem
