### ISSUE TITLE
Unexpected behaviour with easing in animation.finish()

### ISSUE THREAD

**Issue by jonathanasquier** [daniel-lundin/snabbt.js#55]
I started from the drag to flip implementation of the demo. It seems that when using another easing method than linear, the animation does not continue and end smoothly when using animation.finish(), but jumps a bit forward/backward before finishing (obvious when using long durations).

**Comment by daniel-lundin** [comment]
Good catch. Fixed in the latest release 0.5.3.
Let me know if this doesn't fix it.

**Comment by jonathanasquier** [comment]
Works perfectly!

**Comment by jonathanasquier** [comment]
Hi, It seems I'm getting the same issue with rollback : I'm getting a jump forward before rolling back.
Thanks
