### ISSUE TITLE
possible to handle if the animation is started and in progress?

### ISSUE THREAD

**Issue by Kaijun** [daniel-lundin/snabbt.js#57]
I read the API but only found the complete function for the option. Is there any way to handle things when the animation starts and is there also probably a call back function when the animation is in progress?

as i know, velocity has such features.

**Comment by daniel-lundin** [comment]
Sure, a started callback would probably be useful. I'll look into it.

When should the progress-callback be fired?

**Comment by seaneking** [comment]
+1 for the started callback

**Comment by daniel-lundin** [comment]
This is now available in the latest release.

the options are called `start` and `update`. Check the documentation for details:
http://daniel-lundin.github.io/snabbt.js/index.html#api
