### ISSUE TITLE
Anti-aliasing for Firefox

### ISSUE THREAD

**Issue by wayou** [daniel-lundin/snabbt.js#6]
awesome work!

just one problem, we can see apparently  aliasing when open the [demo](http://daniel-lundin.github.io/snabbt.js/cards.html) in Firefox.

**Comment by wayou** [comment]
especially [this one](http://daniel-lundin.github.io/snabbt.js/sticks.html)

**Comment by daniel-lundin** [comment]
It was as simple as adding a `outline: 1px solid transparent;`
