### ISSUE TITLE
Initialize layout with snabbt (duration = 0)

### ISSUE THREAD

**Issue by markmarijnissen** [daniel-lundin/snabbt.js#61]
Can I set initial layout with snabbt?

i.e. use `duration = 0` to set the position immediatly?

This would be very useful to initialize the layout. This way, I don't have to copy the Snabbt.js layout in CSS and I animate from start to end (and back) all using Snabbt.

**Comment by daniel-lundin** [comment]
Hi,

Soon you can, It will be part of next release(just pushed it to master)
I'll see if I can fix some of the other issues before releasing.

**Comment by markmarijnissen** [comment]
Cool! Thanks :) I'll watch the repo for a new release!

**Comment by daniel-lundin** [comment]
I just released v 0.5.5 with this fix included!
