### ISSUE TITLE
Manuel mode problem

### ISSUE THREAD

**Issue by yenerich** [daniel-lundin/snabbt.js#63]
Hi,

I am trying to do this and does not work

var Animacion1 = snabbt(document.querySelectorAll('.multi'), {
  fromPosition: [1000, 50, 0],
  fromRotation: [0, 0, 720],
  delay: function(i) {
    return i * 200;
  },
  easing: 'ease',
  duration: 2500,
  manual: true,
});
   Animacion1.SetValue(1);

Can you point me in the right direction please?

Thanks in advance

**Comment by yenerich** [comment]
Resolved. I was writing SetValue instead of setValue.

**Comment by daniel-lundin** [comment]
👍🏽
