### ISSUE TITLE
Allow adding extra transforms to output

### ISSUE THREAD

**Issue by seaneking** [daniel-lundin/snabbt.js#67]
I keep hitting this roadblock using Snabbt, not sure if it's an issue or I'm just missing something.

**Problem:** if you use CSS transforms that a) you don't want to animate (eg: for positioning), and b) can't be added to Snabbt (eg: percentage offsets) Snabbt clobbers them with it's matrix declaration.

**Possible Solution:** allow the user to mix in in extra transforms with Snabbt's matrix transform, ie: result could be `transform: matrix(...) translateY(-50%)` or whatever. 

An easy fix for this could be adding a new optional property onto Snabbt, something like `staticTransforms:` that just takes a string which is appended onto the end of the matrix transform.

**Comment by daniel-lundin** [comment]
Hmm, interesting. I didn't know it was possible to mix matrix-transform and other(translate/rotate etc.)
It can definitely be added.
The thing is I'm doing kind of a big refactoring of snabbt, moving to es6 with browserify and a lot of tests so I will focus on that branch now.
But if you make a pull request to master I could merge it and make a release. I will add it to the new branch but it will not be released in at least a week,

**Comment by seaneking** [comment]
okay awesome. I'm super busy myself at the moment, but I'll see if I can get a quick PR together.

**Comment by daniel-lundin** [comment]
Hi again,

This is now available in the latest release. It's undocumented at the moment as I want to try it a bit before settling on the exact syntax.
Use it as follows:
```
snabbt(element, {
  position: [100, 0, 0],
  staticTransform: 'translateX(50%)'
});
```

Let me know how it works out for you
