### ISSUE TITLE
Nice work.

### ISSUE THREAD

**Issue by trusktr** [daniel-lundin/snabbt.js#68]
Thanks for the inspiration. :} Some of us in the community are also working on a rendering engine (CSS transforms for DOM, and mixing it with WebGL), discussing and planning over at http://forums.infamous.io.

we're in the process of gathering our ideas by making individual prototypes, learning from the experience, then merging together into a single project. Three of the prototypes so far already work and can render scenes. Those are

- http://github.com/infamous/motor/tree/andrewreedy (by @andrewreedy, demo at http://hybrid-developer.meteor.com/)
- http://github.com/infamous/famin (by @gadicc, demos at http://gadi.cc/famin)
- http://github.com/dmvaldman/samsara (by @dmvaldman, demos at http://samsarajs.org/)

and two prototypes are still a work-in-progress, and will have demos soon:

- http://github.com/infamous/motor/tree/joe (by me)
- http://github.com/infamous/boxer (by @steveblue)

Thought I'd mention our project since we're doing something similar, and we can get inspiration from each other. :}

**Comment by daniel-lundin** [comment]
Nice, I wondered what would happen to famo.us after their pivot. I'll join and try to contribute!
