### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by wayou** [daniel-lundin/snabbt.js#7]
bower support please :)

**Comment by daniel-lundin** [comment]
I'm looking in this. I would like to add AMD-support at the same time for require.js and browserify support.

**Comment by chicoxyzzy** [comment]
Take a look at https://github.com/bebraw/grunt-umd. I think it should help

**Comment by daniel-lundin** [comment]
Cool, I started with my own UMD-boilerplate and added a header and footer with grunt-concat, but this is much cleaner.
Thanks!

**Comment by daniel-lundin** [comment]
Latest release v.0.2.0 is published to bower and npm.
```
bower install snabbt.js
```
