### ISSUE TITLE
simple error report

### ISSUE THREAD

**Issue by dzynx** [daniel-lundin/snabbt.js#72]
"Uncaught TypeError: this.runningAnimations.find is not a function" (from the Console in Chrome version 43.0.2357.81 m)
I don't ask for solution but just post it FYI - if it were an error on my laptop, it can be maybe on other's therefore lowering the popularity/wideness of usage by people/developers.

**Comment by daniel-lundin** [comment]
Thanks for the report. This should actually be fixed in the latest release (0.6.3).
I missed the polyfill when moving to babel earlier.
Which version are you running?

**Comment by daniel-lundin** [comment]
Hi again,
Are you able to reproduce this with the latest release?
I will close this for now, please reopen if you are still experience problems.
