### ISSUE TITLE
Snabbt and Hammer.js

### ISSUE THREAD

**Issue by jonathanasquier** [daniel-lundin/snabbt.js#73]
I working with the drag to flip implementation of the demo (Manual mode).
Finish and rollback work fine since panstop happens when the delta isn't equal to 1 (i.e if I stop swiping before the anim is finished) otherwise animation.finish() is never called and the whole behaviour is broken (breaks the demo)

Thanks

**Comment by daniel-lundin** [comment]
Thanks for the report.
It was a small bug in the complete callback(it was actually executed before the call to finished), it's fixed in the latest release (0.6.4).
