### ISSUE TITLE
slow fps on chrome of android phone

### ISSUE THREAD

**Issue by nvcken** [daniel-lundin/snabbt.js#9]
Hi , it 's cool lib,  but I check example below on chrome of my android phone, the fps is low
http://daniel-lundin.github.io/snabbt.js/sticks.html
Why it happen

**Comment by daniel-lundin** [comment]
The sticks example is a bit extreme for mobile devices, especially older ones.
I will be doing some memory optimizations soon, maybe it will help a bit.
